global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ggcache'
    static_configs:
      - targets: ['172.25.233.25:2222']
        labels:
          service: 'ggcache-1'
      - targets: ['172.25.233.25:2223']
        labels:
          service: 'ggcache-2'
      - targets: ['172.25.233.25:2224']
        labels:
          service: 'ggcache-3'
    metrics_path: '/metrics'

